version: '2'

services:
  app:
    tty: true
    stdin_open: true
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: Dockerfile.development
    command: ./bin/docker_entrypoint.sh server
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:rw,delegated